### ISSUE TITLE
Review Sandbox Model

### ISSUE THREAD

**Issue by zorgiepoo** [zorgiepoo/sparkle-ui-xpc-issues#20]
Current model: sandbox[Application] -> xpc-not-sandboxed[Updater] -> privileged-app[Installer]

Do we want this to also be possible: sandbox[Application & Updater] -> xpc-not-sandboxed[Some Updater Components] -> privileged-app[Installer]

I'm thinking what falls under "some updater components" would be testing writability permissions for automatic updates, and possibly launching the AutoUpdate installer application. The latter would be easy to set up, but would have disadvantages: instability in the updater will affect the app, they must have shared entitlements/exceptions unless they're moved into more XPC components (hard), updater has to stay alive with the app even when idle.

I think:
sandbox[Application] -> xpc-sandbox[Updater] -> xpc-not-sandboxed[Some Updater Components] -> privileged-app[Installer]

would be another possibility, but maybe too difficult. For starters, the updater wouldn't be able to read the bundle from the application as they're sandboxed and different processes.

The simplicity of our current model (the entire of the updater not being sandboxed) means we don't have any XPC services in our framework, but it is a rather large portion of un-sandboxed code..

**Comment by fleyne** [comment]
@zorgiepoo, I have most of my apps sandboxed, and you seems to have thought about Sparkle with sandbox app for long. 
So for the last few hours, I tried to play with your version. But still have some issues.

In your model Sparkle framework is handled by the XPC, no issue on this part.
My issue is in the method checkIfConfiguredProperly. You check the host.bundle vs [NSBundle  mainBundle](as previous master version). 
But this should be always False in this case (as the host.bundle is the main app and NSBundle main is the XPC). Am I missing something ?

More general point on the current topic "Review Sandbox Model". Why not let just the AutoUpdate be in the XPC or other helper or privilege installer? This way the secure download and all other check can be done within the sandbox. And just the AutoUpdate being out of the sandbox. Am I missing something ?

**Comment by zorgiepoo** [comment]
The main bundle checks are a relic from the master branch of Sparkle, and I do indeed need to review those (I created #17 for that). Since I'm using DSA signatures in testing, it hasn't been much of a priority for me to address yet, but it will spew out some warnings.

I'm not sure I'm following your question, but AutoUpdate is intended to act as a "helper" and "potential privileged installer". Due to trust reasons, the last component has to handle extraction, validation, and installing at the minimum. Because this component can potentially use an API for authorization, it cannot be a XPC service (they aren't allowed to do this, even when not sandboxed). Also, XPC services from my experience tend to be tied to the application's lifespan which is also undesirable for the installer.

There are separation benefits (eg: killed when not needed, stability, possibly security) to having Sparkle be in its own XPC service at some complexity which also makes sandboxing Sparkle a little more challenging.

Although there may also be the possibility of having Sparkle and the main app be in the same process, which I think would require us to create XPC services inside the framework.

**Comment by fleyne** [comment]
Sorry for the confusion. I'm not familiar with the full code and architecture. Just had a deeper look today. 

My scenario. Sandbox NSApplication, server with HTTPS.

I notice that the process lead me to an instance of SUBasicUpdateDriver to the following method...
- (void)installWithToolAndRelaunch:(BOOL)relaunch displayingUserInterface:(BOOL)showUI

This method from my understanding is all the last steps of unpacking, signature checking, quarantine, calling the AutoUpdater...

The idea is to launch the XPC service from this last step, just prior the quarantine release (which is not working while sandboxed). 
Then send all the relevant ivar (mainly paths) to the XPC
Then let the XPC service handle only these last steps and then call the AutoUpdater which will proceed normally. The XPC being called with a reply, can close the old app as soon as AutoUpdater quicks in.

This way the XPC is in the Framework. Transparent for the current developers. Most of the operations remains in the main app same process. And the XPC is called really at the last minute (no UI operations at this point anymore).

What would be the down side of this vs an XPC service handling more operation and not sandboxed.

PS: I just tried (with 10.11, modifying the regular Sparkle Master). And this solution is working. I'm concern about the security down side vs your solution. As I'm not an expert.

I hope I'm more clear in my explanations.

**Comment by zorgiepoo** [comment]
> This method from my understanding is all the last steps of unpacking, signature checking, quarantine, calling the AutoUpdater...

Not quite. Extraction and validation actually occur before this method is called. [EDIT]: extraction is done before anyway. In master validation is done inside this method before launching AutoUpdate. But both extraction and validation have to be inside AutoUpdate.

> This way the XPC is in the Framework. Transparent for the current developers. Most of the operations remains in the main app same process. And the XPC is called really at the last minute (no UI operations at this point anymore).

I do want to also look at this being a possibility. Requires creating XPC services in Sparkle (one for downloading, installing/communicating with AutoUpdate, checking writability to my knowledge).

**Comment by fleyne** [comment]
So, all the sensitive part are done within Sandbox within the main app, which is not so bad.

I have posted on my github a working version of what I described previously. It is my first upload ever on github, so I don't know if it is done right. But I highlighted the modified/additional part vs 1.14.  

https://github.com/fleyne/SparkleSandboxXPCTest

The weakest link remains the AutoUpdate. To convert AutoUpdate to a secure helper or XPC, I think it cannot be done. As you need to kill the old app (which launched the helper) before replacing it. And the helper (XPC) will die at the same time. Another solution will be a launchd helper registered by the app. But it will lead to other issues.

Thanks for your insight.

**Comment by zorgiepoo** [comment]
The issue with your fork, as you may be aware, is that it dodges security concerns of the AutoUpdate app trusting the updater. The sensitive parts (extracting, validating, performing installation) can't be done in the sandboxed application.

> To convert AutoUpdate to a secure helper or XPC, I think it cannot be done. As you need to kill the old app (which launched the helper) before replacing it. And the helper (XPC) will die at the same time.

It sure can't be a XPC service. At the moment, I'm launching AutoUpdate using launch services from a non-sandboxed XPC service. If you launch a task (eg: NSTask), I've found that the process can just die off when the app terminates.. from my experience.

> Another solution will be a launchd helper registered by the app. But it will lead to other issues.

Indeed, and this may even be able to use the XPC APIs. But this sort of solution is not one that I want to adventure towards right now.

**Comment by fleyne** [comment]
I may have not understood something then.

From my understanding of my fork (tried with a sandbox app) : The downloading, the extracting, validating is done within the sandbox. This is not a problem as the extraction is performed within the sandbox container (Caches).

Just before the removal of the quarantine, the XPC (non sandboxed) is launched to perform this operation as the removal of the quarantine was not working in the Sandbox. Then the XPC is launching the AutoUpdate just to perform the final copy. This is why I see the AutoUpdate as a weak link.
I could reinforce the Autoupdate security by passing from the sandbox to the Autoupdate the SHA1 or other checksum to check before copying.

What I was surprised (I agree with you) is the Autoupdate is not dying when the old app is terminated. Which was a surprise for me. As the AutoUpdate, launched by the XPC linked to the old app should die too.

The launchd helper (sandboxed) yes can use XPC APIs. I'm using this architecture (for another purpose) in one of my app.

**Comment by zorgiepoo** [comment]
> From my understanding of my fork (tried with a sandbox app) : The downloading, the extracting, validating is done within the sandbox. This is not a problem as the extraction is performed within the sandbox container (Caches).

The reason why previous sandbox forks were rejected from being merged into Sparkle are because the "extracting, validating, installation" are not done in the same process. If AutoUpdate doesn't do the extraction and validation, then it's trusting whatever comes before it, which is the problem.

> What I was surprised (I agree with you) is the Autoupdate is not dying when the old app is terminated. Which was a surprise for me. As the AutoUpdate, launched by the XPC linked to the old app should die too.

I would test by doing a sleep(20) somewhere in AutoUpdate to really be certain that it may not automatically die off when spawned as a task.

> The launchd helper (sandboxed) yes can use XPC APIs. I'm using this architecture (for another purpose) in one of my app.

Yep. Like above, the launchd helper can't trust whatever is communicating to it though. I have tested the `SMJobBless()` samples out before; basically anything can communicate to the helper (only during installing the tool, code signature verification may be checked). Apple's sample code touches on this topic too.

**Comment by zorgiepoo** [comment]
Ok, looks like AutoUpdate doesn't die for me either when spawned as a task. On the contrary, using LaunchServices doesn't work right for me anymore when I started to create a XPC service for launching AutoUpdate..

So I recently created a few XPC services inside the framework so it can just be dropped in an existing app, without having to put Sparkle in a separate process/service entirely. The only entitlement that is still needed (at the moment) is a mach service lookup for communicating to the installer:

```
   <key>com.apple.security.temporary-exception.mach-lookup.global-name</key>
   <array>
       <string><app-bundle-id>-sparkle-installer</string>
   </array>
```

**Comment by fleyne** [comment]
> The reason why previous sandbox forks were rejected from being merged into Sparkle are because the "extracting, validating, installation" are not done in the same process. If AutoUpdate doesn't do the extraction and validation, then it's trusting whatever comes before it, which is the problem.

Oh Yes I forgot @pornel first post of the thread few years back.
On the other hand, the actual master of Sparkle let AutoUpdate trust what is sent to him.

> Ok, looks like AutoUpdate doesn't die for me either when spawned as a task. On the contrary, using LaunchServices doesn't work right for me anymore when I started to create a XPC service for launching AutoUpdate..

I think the AutoUpdate is not dying because the process which spawn it (the XPC) is not sandboxed. I think the child process dying is related to the sandbox restrictions.
LaunchServices can be tricky while sandboxed. For example my other app using this (fully sandboxed), needs to be located in /Applications folder. The service being in the app. Otherwise the system will fail to launch it.

> So I recently created a few XPC services inside the framework so it can just be dropped in an existing app, without having to put Sparkle in a separate process/service entirely. The only entitlement that is still needed (at the moment) is a mach service lookup for communicating to the installer:

How do you launch the XPC services? Why do you need the extra mach entitlement? Are all your XPC services sandboxed? I think, the installer cannot be sandboxed. Do you have an example on github for me to have a look.
I think Sparkle entirely need to end up as separated process/service.

**Comment by zorgiepoo** [comment]
> Oh Yes I forgot @pornel first post of the thread few years back.
> On the other hand, the actual master of Sparkle let AutoUpdate trust what is sent to him.

Yep, it's an issue in master too.

> I think the AutoUpdate is not dying because the process which spawn it (the XPC) is not sandboxed. I think the child process dying is related to the sandbox restrictions.
> LaunchServices can be tricky while sandboxed. For example my other app using this (fully sandboxed), needs to be located in /Applications folder. The service being in the app. Otherwise the system will fail to launch it.

When I was sticking the entirety of Sparkle in a non-sandboxed process, I saw my spawned task die at an unpredictable time after the main app terminated. But now I have Sparkle launching a XPC service to launch AutoUpdate. There are two things I can think that have changed since: the XPC service I recently wrote doesn't use NSRunLoop as the runloop type in the XPC service info.plist, and I don't have AutoUpdate displaying any UI at the moment.

> How do you launch the XPC services? Why do you need the extra mach entitlement? Are all your XPC services sandboxed? I think, the installer cannot be sandboxed. Do you have an example on github for me to have a look.

The installer (AutoUpdate) is not sandboxed. The XPC services whose task is to download files are sandboxed with a client-network entitlement. The other XPC service I've written to launch AutoUpdate and test for install writability is not sandboxed. The XPC service that I will write in the future to remove the extra mach entitlement probably won't be sandboxed (it could be, but it would require configuration from the user end..). I use mach ports/service for IPC communication between Sparkle and AutoUpdate (this should be a valid technique for launchd type service too).

I think the Test Application in my fork should be okay to look at right now. I sometimes swap out things in the test app for testing (for example, testing putting Sparkle in its own process, versus not doing that, versus using a custom or standard UI).

> I think Sparkle entirely need to end up as separated process/service.

What makes you think this? Technical reasons, or security reasons? Are you referring to AutoUpdate and Sparkle being merged, or are you referring to the main app and Sparkle being separated (the latter of which my fork supports as an option).

**Comment by fleyne** [comment]
> When I was sticking the entirety of Sparkle in a non-sandboxed process, I saw my spawned task die at an unpredictable time after the main app terminated. But now I have Sparkle launching a XPC service to launch AutoUpdate. There are two things I can think that have changed since: the XPC service I recently wrote doesn't use NSRunLoop as the runloop type in the XPC service info.plist, and I don't have AutoUpdate displaying any UI at the moment.

I don't use NSRunLoop for my XPC services.
You said Sparkle was in a non-sandboxed process. But it was spawn by a sandboxed process.
Now you have Sparkle (Sandboxed) launching a XPC service (non sandboxed) launching Autoupdate.
I think the restriction is when a sandbox process A spawn a child process B (sandboxed or not). the process B life span is linked to the sandboxed process A. I need to go back to check the sandbox restrictions, but I think it is what happen.

I will re-download your fork to have a look then.

> What makes you think this? Technical reasons, or security reasons? Are you referring to AutoUpdate and Sparkle being merged, or are you referring to the main app and Sparkle being separated (the latter of which my fork supports as an option).

I take as working idea @pornel point, to not have the AutoUpdate trust what is sent to him (security). In this case a big part of Sparkle will be handled by this new process/service. It is a big change compare to the actual architecture. 
So except if I miss something, in this case you are going to end up with more less this already. 
Sparkle and AutoUpdate being merged. This new process being separated from the main app. Did I miss something?

**Comment by zorgiepoo** [comment]
I got launching by LaunchServices to work again. I was making a really dumb mistake by trying to launch the executable rather than the app bundle path :|. `AuthorizationExecuteWithPrivileges` can't be used from a task that is spawned from a XPC service (sandboxed or not), so this is the only choice I have as far as restrictions go.

I'm not sure I'm following what you're saying, but I don't want to have Sparkle and AutoUpdate be merged, and I don't think it's necessary. As long as the last component does the extraction and validation, I think trust should be fine. AutoUpdate should also not perform any work that it doesn't have to, because one day it could be swapped out with something that runs entirely as a privileged process.

I also want to consider for example using `SMJobSubmit` instead of launching AutoUpdate directly, and specifying ahead of time whether we will need to do privileged operations or not. I'm not entirely sure how well this would work out though and am concerned about future reliability issues.

**Comment by fleyne** [comment]
> I'm not sure I'm following what you're saying, but I don't want to have Sparkle and AutoUpdate be merged, and I don't think it's necessary. As long as the last component does the extraction and validation, I think trust should be fine. AutoUpdate should also not perform any work that it doesn't have to, because one day it could be swapped out with something that runs entirely as a privileged process.

Actually yes, you are right. I had a deeper look today at your last fork, and it is quite nice actually. I had actually missed the IPC changed you made previously. And the new XPC services are better than before.
I have a question about IPC. I'm not very good about the inner working and mechanism of IPC. But what happen when 2 different apps are running the Sparkle update? And you have 2 AutoUpdate processes running ? 

> I also want to consider for example using SMJobSubmit instead of launching AutoUpdate directly, and specifying ahead of time whether we will need to do privileged operations or not. I'm not entirely sure how well this would work out though and am concerned about future reliability issues.

I think this one is trickier.

**Comment by zorgiepoo** [comment]
Yeah, two different AutoUpdate processes running. The uniqueness is dependent on the bundle ID of the app that is being updated - so I suppose it wouldn't (or shouldn't) be possible for two different versions of the same app being updated simultaneously.

**Comment by fleyne** [comment]
Oops yes. I missed the SUxxxxxxxxServiceNameForBundleIdentifier.
