### ISSUE TITLE
Remove mach-lookup.global-name entitlement requirement

### ISSUE THREAD

**Issue by zorgiepoo** [zorgiepoo/sparkle-ui-xpc-issues#25]
I'll need to create a XPC service that wraps around SURemoteMessagePort. It probably won't be sandboxed because the entitlement string would differ based on the app that is being installed. Currently the value string is in this format: <app-bundle-id>-sparkle-installer

Fortunately SURemoteMessagePort is already (mostly) an async API. Synchronous code that sees if the initializer succeeds will need to change.

**Comment by fleyne** [comment]
Yes, XPC service would be better instead of the current extra entitlement.

**Comment by zorgiepoo** [comment]
This should be handled now.
