### ISSUE TITLE
css not applied to release notes

### ISSUE THREAD

**Issue by sweetppro** [zorgiepoo/sparkle-ui-xpc-issues#35]
when I add release notes to the app cast like so:

```
<sparkle:releaseNotesLink>
https://mydomain.com/myapp/updates.htm
</sparkle:releaseNotesLink>
```

I import css into my updates.htm

```
<link href="../../css/updater.css" rel="stylesheet" type="text/css" />
<style type="text/css"></style>
```

this works in the official release of Sparkle, but not this XPC branch.
is there something else I need to do to get my custom css displaying?

should I be providing an absolute url for the css?

**Comment by zorgiepoo** [comment]
I can guess the issue. I had to treat downloading external release notes specially by downloading that file inside a XPC service (so the main app doesn't need an entitlement for downloading files). The web view in the sandboxed app is trying to resolve external references and failing though.. An easy workaround for now may be including the css in the html file, or to give your app the extra entitlement (probably undesirable).

(Off topic: I recently rewrote a large portion of the update-installer interaction this fork uses btw)

**Comment by sweetppro** [comment]
ah ok,
Ill just add the css inline.

great fork by the way,
apart from this small issue, "upgrading" from the official fork was super easy.
thanks!

**Comment by sweetppro** [comment]
just following up. using absolute links in my css, and html file fixed all issues

**Comment by zorgiepoo** [comment]
Ok, relative linking should now work due to https://github.com/zorgiepoo/Sparkle/commit/97eb25b27fc3852d9a740093972db5b43e358165

However you'd still need to either be not sandboxed or have a com.apple.security.network.client entitlement to load external files from the release notes. If you think you're fully sandboxed and external loading works there, then you're not actually being sandboxed.

**Comment by sweetppro** [comment]
ah ok, i do have the com.apple.security.network.client entitlement.
thanks for the patch for relative links.
:)
