### ISSUE TITLE
Failed to make auth right set

### ISSUE THREAD

**Issue by dsanghan** [zorgiepoo/sparkle-ui-xpc-issues#39]
My app is both code-signed and sandboxed. 

I added the InstallerLauncher/Status/Connection XPC's and the Sparkle framework. I have the outgoing HTTP entitlement and so did not add the Downloader service.

When I do a check for updates, it successfully finds the version and downloads it.

Unfortunately it cannot install it. The installer xpc fails to get the auth rights required to execute.

I noted the following in the logs:

```
9/29/16 1:00:20.766 PM org.sparkle-project.InstallerLauncher.xpc [Sparkle][14403]: Failed to make auth right set
9/29/16 1:00:20.000 PM kernel[0]: Sandbox: org.sparkle-proj(14403) deny(1) authorization-right-obtain <bundle-id>.sparkle-auth
9/29/16 1:00:20.766 PM authd[126]: Sandbox denied authorizing right '<bundle-id>.sparkle-auth' by client '/Applications/[App Name].app/Contents/XPCServices/org.sparkle-project.InstallerLauncher.xpc' [14403]
9/29/16 1:00:20.766 PM org.sparkle-project.InstallerLauncher.xpc [Sparkle][14403]: Failed copying system domain rights: -60005
9/29/16 1:00:20.766 PM org.sparkle-project.InstallerLauncher.xpc [Sparkle][14403]: Failed to submit installer job
9/29/16 1:00:20.766 PM [App Name] [Sparkle][14398]: Error: Failed to gain authorization required to update target
9/29/16 1:00:22.524 PM [App Name] [Sparkle][14398]: Error: An error occurred while launching the installer. Please try again later. (null) (URL (null))
```

The system domain rights: -60005 corresponds to errAuthorizationDenied. It also seems like sandboxed apps don't have the ability to use [Authorization Services](https://developer.apple.com/library/content/documentation/Security/Conceptual/AppSandboxDesignGuide/DesigningYourSandbox/DesigningYourSandbox.html#//apple_ref/doc/uid/TP40011183-CH4-SW6).

As noted in the INSTALL file, I've code-signed my XPC services/framework and made sure that they have the sandbox + HTTP client entitlements.

**Comment by dsanghan** [comment]
EDIT: Ok, so I got it to work by removing the sandbox entitlement while code-signing the XPC services.

**Comment by zorgiepoo** [comment]
How were you code signing the services? The InstallerLauncher service (same goes with InstallerStatus and InstallerConnection) in particular is not supposed to be sandboxed and not supposed to have any entitlements.

**Comment by dsanghan** [comment]
Yeah, I am code signing them. I was assuming I should add a basic sandboxed entitlement but shouldn't have. Works well now without entitlements.

**Comment by zorgiepoo** [comment]
Note the Downloader XPC service can have entitlements (with an exception for client connections).

As explained in the `INSTALL` I provided a `codesign_xpc` script so that people wouldn't make the mistake of signing these services incorrectly.

**Comment by dsanghan** [comment]
Yup, makes sense, I had a --deep going on which I figured would be fine and wasn't. Thanks for the great fork!

**Comment by zorgiepoo** [comment]
Yeah, this kind of scenario explains why Apple discourages using --deep when signing.

**Comment by SevenBits** [comment]
@zorgiepoo I just started setting up your package in my app, and I’m having the same issue. What I did was:

- Downloaded the source files from GitHub. Built with `make release`.
- Copied Sparkle.framework, and the installer connection, status, and launcher XPCs. These XPCs were code signed with the provided script.
- Added XPCs to project, set them up to copy to the XPC services directory.
- Started the update. The download completes as expected but then fails when the “Install and Relaunch” button would normally activate. The message given in the `NSAlert` is: “An error occurred while launching the installer. Please try again later.”

I see the following in the logs:

> Dec 22 11:58:16  Mac Linux USB Loader [Sparkle][2944] <Error>: Failed to make auth right set
Dec 22 11:58:16  Mac Linux USB Loader [Sparkle][2944] <Error>: Failed to open temp icon from path buffer with error: 1
Dec 22 11:58:16  Mac Linux USB Loader [Sparkle][2944] <Error>: Failed copying system domain rights: -60005
Dec 22 11:58:16  Mac Linux USB Loader [Sparkle][2944] <Error>: Failed to submit installer job
Dec 22 11:58:16  Mac Linux USB Loader [Sparkle][2944] <Error>: Error: Failed to gain authorization required to update target
Dec 22 11:58:18  Mac Linux USB Loader [Sparkle][2944] <Error>: Error: An error occurred while launching the installer. Please try again later. (null) (URL (null))

I’ve followed the `INSTALL` file as close as possible. How should I try to debug this?

**Comment by zorgiepoo** [comment]
The original poster was having this issue because they were signing all the services with a sandboxed entitlement -- you could check the final built product and see if there are entitlements attached to the services, perhaps.

The code determined that admin authorization was necessary. Were you updating at a location that you don't have write permission to? (I'd test Sparkle in both cases). It seems like writing to /tmp also failed.

Did you at any point re-sign the services? Perhaps inside Xcode or during an archive export.

**Comment by SevenBits** [comment]
@zorgiepoo So, I made at least a little bit of progress. The XPC services were not being copied over properly by Xcode.

Now, I can get a little further, but there’s still a similar issue. Here’s the logs again:

> Dec 22 12:40:19  org.sparkle-project.InstallerLauncher.xpc [Sparkle][3552] <Error>: Error: Cannot submit progress tool because the progress tool could not be located
Dec 22 12:40:19  Mac Linux USB Loader [Sparkle][3545] <Error>: Error: Failed to gain authorization required to update target
Dec 22 12:40:22  Mac Linux USB Loader [Sparkle][3545] <Error>: Error: An error occurred while launching the installer. Please try again later. (null) (URL (null))

I’m testing the app right now by launching it from Xcode, and having it “update” to another copy of the app that I have stored locally (being served over localhost).

I don’t think I re-signed anything, but I can double check.

**Comment by zorgiepoo** [comment]
Seems like a different issue. The Updater.app was not found in the InstallerLauncher XPC service (in Contents/MacOS)

**Comment by SevenBits** [comment]
@zorgiepoo That was it, thank you!
