### ISSUE TITLE
Incorrect version displayed in dialog about new update...

### ISSUE THREAD

**Issue by digitalmoksha** [zorgiepoo/sparkle-ui-xpc-issues#42]
I use the CFBundleShortVersionString for the normal, user facing version number (such as `1.5.4`), and the CFBundleVersion for an always incrementing build number (such as `301`).

When a new update is available, I get a dialog with incorrect version strings shown:

```
A new version of My App is available!

My App 301 is now available - you have 1.5.2.  Would you like to download it now?
```

It seems to be using the CFBundleVersion for the newest version, and CFBundleShortVersionString for the previous version.

I'm using the delta updates, and at the moment the default appcast which is generated by `generate_appcast` (which has no release notes).

**Comment by zorgiepoo** [comment]
It depends on `sparkle:shortVersionString` being set in the appcast, same as the `master` branch in the official repo.

**Comment by digitalmoksha** [comment]
ah, it's not being added by the `generate_appcast` tool.  I'll open an issue on that in the main repo.
